### ISSUE TITLE
pthread error

### ISSUE THREAD

**Issue by hurnhu** [lnishan/TwitchPlaysAPI#1]
i just get the error
'1>TwitchPlaysAPI.obj : error LNK2019: unresolved external symbol _pthread_create referenced in function "public: bool __thiscall TwitchPlays::start(void)" (?start@TwitchPlays@@QAE_NXZ)
1>TwitchPlaysAPI.obj : error LNK2019: unresolved external symbol _pthread_exit referenced in function "void \* __cdecl inputThread(void *)" (?inputThread@@YAPAXPAX@Z)'
also in the linker -> input -> additional dependecies. i added pthreadVC2.lib

**Comment by lnishan** [comment]
Sorry for the delay.

I had a quick look and unfortunately this repo wasn't correctly configured. (ie. Some necessary files are clearly missing as you've already noted.)  
I have compressed the whole project including all the necessary files. [Try this](https://drive.google.com/file/d/0B7xu0NquEWkfSmdGc05MNHNrelU/view?usp=sharing) (Note that this requires VC12)

**Comment by hurnhu** [comment]
thanks :) also i see there are commands? how do i use them? oh and ps i upgraded your code to use the non deprecated vr of gethostbyname.

**Comment by lnishan** [comment]
In terms of the core IRC client, major credits go to [Fredy's IRC Client](https://github.com/Fredi/IRCClient) :)

What I did was fixing bugs (There were a few bugs which cause the client to crash under high chat activity) and changing threading library and interface so that it hides the IRC client itself well beneath user space.

The core functionality is limited (I didn't need much for my Connect6 game :P). Set-up the config file and you get 4 functions:  
1. Initialize the client (read config file)
2. Hook your event (make a function that takes 2 strings, first being the sender, second being the message)
3. Start the client, and the client would work on its own thread.
4. Stop the client anytime you want.

Refer to [Main.cpp](https://github.com/lnishan/TwitchPlaysAPI/blob/master/Main.cpp) for what I mentioned above.

Good luck on your project ;)
